# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz_18' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quiz_18
  pod 'Kanna','~>5.0.0' 

end
